<!-- Generated from ${context._with_template.uri} for ${lib_name} -->
<package>
    <description brief="Robotic data types autogenerated for TASTE">
        This ${lib_name} package is autogenerated from ${lib_name}.tlb
    </description>
    <author>GMV Aerospace &amp; Defence S.A.U.</author>
    <copyright>GMV 2018</copyright>
    <license>GPLv2</license>
    <depend package="tools/config" />
</package>
